# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfgAvunGiqw-iiHtWbRex2x7IKvae4Wm
"""

!pip install langchain==0.2.1 langchain-core==0.2.1 langchain-community==0.2.1

pip install langchain-community

!pip install faiss-cpu

!pip install -U bitsandbytes

!pip install -U bitsandbytes accelerate transformers

!pip install -U langchain

!pip install -U transformers accelerate bitsandbytes

!pip install -U langchain langchain-community langchain-core
!pip install -U faiss-cpu
!pip install -U sentence-transformers
!pip install -U transformers

import torch
import pandas as pd

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.document_loaders import DataFrameLoader
from langchain_community.llms import HuggingFacePipeline

from transformers import AutoTokenizer, pipeline

from google.colab import files
uploaded = files.upload()

data = pd.read_csv('GroceryDataset.csv').dropna().reset_index(drop=True)

# This function takes a single row (x) from the dataset
# and combines multiple columns into one clean text block.
# The output is a structured product description that includes:
# - product title
# - category
# - features
# - full description
# This combined text will later be used for embeddings in RAG.
def get_description(x):
    return f"""Product title:
{x['Title']}
Product category:
{x['Sub Category']}
Product features:
{x['Feature']}
Product description:
{x['Product Description']}
"""

#getting the full document description:
# Apply the get_description function to every row in the dataset
# This creates a new column called "Full Description"
# Each row will now contain a combined text version of all product details
data['Full Description'] = data.apply(get_description, axis=1)
data.head()

print(data['Full Description'][0])

# Create an embedding model using a pre-trained SentenceTransformer
# This model converts text into numerical vectors (embeddings)
# These embeddings are used to measure similarity between documents in RAG

embedder = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2",  # lightweight sentence embedding model
    model_kwargs={"device": "cuda"},  # run on GPU
    encode_kwargs={"normalize_embeddings": False}  # do not normalize vector values
)

import torch
print(torch.cuda.is_available())

# Create HuggingFace embedding model for LangChain
embedder = HuggingFaceEmbeddings(
    model_name=modelPath,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs
)

# Import tool that converts a pandas DataFrame into LangChain documents
from langchain_community.document_loaders import DataFrameLoader

# This function turns a dataset column into a list of documents
# Each row becomes one document (used for embeddings later)
def get_documents(data, page_content_column):
    return DataFrameLoader(data, page_content_column=page_content_column).load()


documents = get_documents(data, 'Full Description')          # Create documents using the full product description column
documents2 = get_documents(data, 'Product Description')      # Create another set of documents using only the short product description
print(f'We have {len(documents)} context in total\n')        # Print how many documents were created (to check dataset size)

query = "Cookies Mile High Peanut Butter Cake"             # Define a search query (what we want to find in the dataset)
db2 = FAISS.from_documents(documents2, embedder)           # Create a FAISS vector database from the documents (# FAISS converts all documents into embeddings and stores them for fast search)
db2.similarity_search(query, k=1)                          # Search for the most similar document to the query (# k=1 means we only want the single most relevant result)

db = FAISS.from_documents(documents, embedder)    # Create FAISS database (stores text as vectors for search)
db.similarity_search(query, k=1)                  # Find the most similar document to the query

# Import required libraries for loading and running the model
import torch
import transformers
from transformers import AutoModelForCausalLM, AutoTokenizer

# Model name (pretrained chat model from Hugging Face)
model_id = "mistralai/Mistral-7B-Instruct-v0.1"

# Settings to make the model smaller and faster using 4-bit loading
bnb_config = transformers.BitsAndBytesConfig(
    load_in_4bit=True,  # reduce memory usage
    bnb_4bit_use_double_quant=True,  # better compression
    bnb_4bit_quant_type="nf4",  # quantization method
    bnb_4bit_compute_dtype=torch.float16  # faster computation
)

# Load the language model
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",  # automatically use CPU or GPU if available
    torch_dtype=torch.float16,  # use half precision for speed
    trust_remote_code=True  # allow custom model code
)

# Load tokenizer (converts text ↔ numbers so model can understand input/output)
tokenizer = AutoTokenizer.from_pretrained(model_id)

"""Create AI Text Generator"""

# Create a text generator using the model and tokenizer
# It makes the model write answers from a prompt
pipe = pipeline(
    "text-generation",   # tells model to generate text
    model=model,         # the AI model
    tokenizer=tokenizer, # helps convert text to numbers and back
    max_new_tokens=200   # limits how long the answer can be
)

# Make the model usable in LangChain
# This lets us use it in RAG
hf = HuggingFacePipeline(pipeline=pipe)

"""**RAG Pipeline**"""

from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_community.llms import HuggingFacePipeline
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough, RunnableLambda

##Prompt
# This is the instruction format given to the AI model

# The model is told to:
# - ONLY use the provided context (no outside knowledge)
# - read the context
# - then answer the question
# The [INST] ... [/INST] format is required by Mistral models to structure instructions properly
prompt_template = """
[INST]
Answer ONLY using the context below.

Context:
{context}

Question:
{question}
[/INST]
"""

# Create a prompt object that defines what inputs the AI needs
# It tells the model we will give:
# - context (extra information from documents)
# - question (user's question)

prompt = PromptTemplate(
    input_variables=["context", "question"],  # required inputs for the prompt
    template=prompt_template,                 # the format of the instruction
)

"""Build Input Function for RAG Pipeline (Retrieval + Context Preparation)"""

# This function prepares input for the RAG system

# It takes the user question and:
# 1. Finds similar documents from the database
# 2. Combines them into a single context
# 3. Returns both context and question for the AI

def build_inputs(inputs):

    # If input is just a text string, treat it as the question
    if isinstance(inputs, str):
        question = inputs
    else:
        # If input is a dictionary, extract the question
        question = inputs.get("question")

    # Search for similar documents in FAISS database
    docs = db.as_retriever().invoke(question)

    # Join all found documents into one text (context)
    context = "\n".join([d.page_content for d in docs])

    # Return both context and question for the model
    return {
        "context": context,
        "question": question
    }

# RAG CHAIN
# This is the RAG system (chat with documents)

# It works in 3 steps:
# 1. Find related documents
# 2. Put them into a question format
# 3. Ask the AI model to answer

rag_chain = (
    RunnableLambda(build_inputs)  # gets related text from database
    | prompt                       # prepares the question format
    | hf                           # AI writes the final answer
)

# This function cleans the AI output (final answer)

# It makes sure the output is always readable text


def parse_answer(output):
    if isinstance(output, str):
        # Strip everything up to and including [/INST]
        if "[/INST]" in output:
            return output.split("[/INST]")[-1].strip()
        return output.strip()
    if isinstance(output, dict):
        text = output.get("text", str(output))
        if "[/INST]" in text:
            return text.split("[/INST]")[-1].strip()
        return text.strip()
    return str(output)

# This sends a question to the RAG system

# Step 1: user question is sent
# Step 2: system finds relevant documents
# Step 3: AI generates an answer

result = rag_chain.invoke({
    "question": "Tell me about David's Cookies Butter Pecan Meltaways"
})

# Clean and print the final answer
print(parse_answer(result))

result = rag_chain.invoke({
    "question": "What is the price of David’s Cookies Mile High Peanut Butter Cake?"
})

print(parse_answer(result))

result = rag_chain.invoke({
    "question": "What is the rating of David’s Cookies Premier Chocolate Cake?"
})

print(parse_answer(result))

result = rag_chain.invoke({
    "question": "List top products under the Beverages & Water category. Show only names"
})

print(parse_answer(result))

